version : '2'
services:

  db:
    container_name: bdd
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=yamine
      - MYSQL_PASSWORD=yamine
      - MYSQL_DATABASE=ecole
      - MYSQL_ALLOW_EMPTY_PASSWORD=non
    networks:
      - networkApplication

  web:
    build: .
    image: application
    restart: always
    depends_on:
      - db
    ports:
      - '80:8080'
    networks:
      - networkApplication

networks:
  networkApplication:
    driver: bridge

  
      

        
        
        